// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsLS_rz8elEsmRacp5mcGo3PZN6Xy_Rw',
    appId: '1:292650825275:web:17cbf9eded9cc00ca08e1e',
    messagingSenderId: '292650825275',
    projectId: 'mundopc-58433',
    authDomain: 'mundopc-58433.firebaseapp.com',
    storageBucket: 'mundopc-58433.appspot.com',
    measurementId: 'G-X95HR9Y52R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBysEp6Sa2IFxNwO1lqchfDev18pfVB1D8',
    appId: '1:292650825275:android:8b8115bf7fb417fba08e1e',
    messagingSenderId: '292650825275',
    projectId: 'mundopc-58433',
    storageBucket: 'mundopc-58433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66Zro0MxnOZkNAaVCvSDJO8ofDV3U0Hg',
    appId: '1:292650825275:ios:afd70ecaff4d94a5a08e1e',
    messagingSenderId: '292650825275',
    projectId: 'mundopc-58433',
    storageBucket: 'mundopc-58433.appspot.com',
    iosBundleId: 'com.example.devTesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66Zro0MxnOZkNAaVCvSDJO8ofDV3U0Hg',
    appId: '1:292650825275:ios:afd70ecaff4d94a5a08e1e',
    messagingSenderId: '292650825275',
    projectId: 'mundopc-58433',
    storageBucket: 'mundopc-58433.appspot.com',
    iosBundleId: 'com.example.devTesis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjsLS_rz8elEsmRacp5mcGo3PZN6Xy_Rw',
    appId: '1:292650825275:web:5d851c0820f79fc6a08e1e',
    messagingSenderId: '292650825275',
    projectId: 'mundopc-58433',
    authDomain: 'mundopc-58433.firebaseapp.com',
    storageBucket: 'mundopc-58433.appspot.com',
    measurementId: 'G-KESV5DTEYH',
  );

}