// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBjsLS_rz8elEsmRacp5mcGo3PZN6Xy_Rw",
      authDomain: "mundopc-58433.firebaseapp.com",
      projectId: "mundopc-58433",
      storageBucket: "mundopc-58433.appspot.com",
      messagingSenderId: "292650825275",
      appId: "1:292650825275:web:8cd22c8c6397f96fa08e1e",
      measurementId: "G-41FR0DM8SF");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjsLS_rz8elEsmRacp5mcGo3PZN6Xy_Rw',
    appId: "1:292650825275:web:8cd22c8c6397f96fa08e1e",
    messagingSenderId: "292650825275",
    projectId: "mundopc",
    storageBucket: 'mundopc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeAJETe6eYIQj0zszwdfsFZTaDWvjCYYU',
    appId: '1:976426204856:ios:ab03036dc7dc63d76dbe4d',
    messagingSenderId: '976426204856',
    projectId: 'club-delfines-panel',
    storageBucket: 'club-delfines-panel.appspot.com',
    iosClientId:
        '976426204856-atvg010ctoqfuidl34ju6mf7rtt69h3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubdelfinespanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeAJETe6eYIQj0zszwdfsFZTaDWvjCYYU',
    appId: '1:976426204856:ios:fce3ebd9cc43c7566dbe4d',
    messagingSenderId: '976426204856',
    projectId: 'club-delfines-panel',
    storageBucket: 'club-delfines-panel.appspot.com',
    iosClientId:
        '976426204856-oj3mbv8biua5dvk4kq54nilafae0ue8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubdelfinespanel.RunnerTests',
  );
}
